Models/Entities/Event.cs
namespace EventManagementSystem.Models.Entities
{
    public class Event
    {
        public Guid Id { get; set; }

        public string? Name { get; set; }

        public string? Description { get; set; }

        public int Price { get; set; }

        public DateTime Date { get; set; }

        public ICollection<Review> Reviews { get; set; }
        public ICollection<EventList> EventLists { get; set; }
    }
}

Controllers/EventsController.cs
using EventManagementSystem.Data;
using EventManagementSystem.Models;
using EventManagementSystem.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EventManagementSystem.Controllers
{
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public EventsController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddEventViewModel viewModel)
        {
            var eventDetails = new Event {
                Name = viewModel.Name,
                Price = viewModel.Price,
                Description = viewModel.Description,
                Date = viewModel.Date
            };

            await dbContext.Events.AddAsync(eventDetails);
            await dbContext.SaveChangesAsync();

            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var events = await dbContext.Events.ToListAsync();
            return View(events);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var eventDetails = await dbContext.Events.FindAsync(id);

            return View(eventDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Event viewModel)
        {
            var eventDetails = await dbContext.Events.AsNoTracking().FirstOrDefaultAsync(x => x.Id == viewModel.Id);

            if (eventDetails is not null)
            {
                dbContext.Events.Remove(viewModel);
                await dbContext.SaveChangesAsync();
            }

            return RedirectToAction("List", "Events");
        }
    }
}

Controllers/ReviewsController.cs
using EventManagementSystem.Data;
using EventManagementSystem.Models;
using EventManagementSystem.Models.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EventManagementSystem.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public ReviewsController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Add(Guid id)
        {
            var eventDetails = await dbContext.Events.FindAsync(id);

            var eventModelReview = new ReviewViewModel();
            if (eventDetails != null)
            {
                eventModelReview.EventId = eventDetails.Id;
                eventModelReview.EventName = eventDetails.Name;
            }

            return View(eventModelReview);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ReviewViewModel viewModel)
        {
            var idString = HttpContext.Session.GetString("UserId");

            if (!Guid.TryParse(idString, out Guid id))
            {
                // Handle the case where the session value is not a valid Guid
                // For example, redirect to an error page or display an error message
            }

            var reviewDetails = new Review
            {
                EventId = viewModel.EventId,
                UserId = id,
                Message = viewModel.Message,
                Rating = viewModel.Rating,
            };

            await dbContext.Reviews.AddAsync(reviewDetails);
            await dbContext.SaveChangesAsync();

            return RedirectToAction("List", "Events");
        }

        [HttpGet]
        public async Task<IActionResult> List(Guid id)
        {
            var reviews = await dbContext.Reviews
                .Include(r => r.User)
                .Include(r => r.Event)
                .Where(r => r.EventId == id)
                .Select(r => new ReviewViewModel
                {
                    EventId = r.EventId,
                    UserName = r.User.Name,
                    EventName = r.Event.Name,
                    Rating = r.Rating,
                    Message = r.Message
                })
                .ToListAsync();
            return View(reviews);
        }
    }
}

Views/Events/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model EventManagementSystem.Models.AddEventViewModel

<div class="lg:w-50 mx-lg-auto">
    <h2>Add Event</h2>

    <div>
        <form method="post">
            <div class="form-group">
                <label class="form-label" for="event-name">Name</label>
                <input class="form-control" type="text" id="event-name" asp-for="Name" />
            </div>

            <div class="form-group">
                <label class="form-label" for="event-price">Price</label>
                <input class="form-control" type="number" id="event-price" asp-for="Price" />
            </div>

            <div class="form-group">
                <label class="form-label" for="event-description">Description</label>
                <input class="form-control" type="text" id="event-description" asp-for="Description" />
            </div>

            <div class="form-group">
                <label class="form-label">Date and Time</label>
                <input class="form-control" type="datetime-local" id="event-date" asp-for="Date" />
            </div>

            <button type="submit" class="btn btn-primary mt-3">Add Event</button>
        </form>
    </div>
</div>

Views/Events/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model EventManagementSystem.Models.Entities.Event

<h1>Event Details</h1>

@if(Model is not null)
{
    <div class="card card-body mb-3">
        <h2>Name: @Model.Name</h2>
        <h3>Price: $@Model.Price</h3>
        <p>Description: @Model.Description</p>
        <span>@Model.Date</span>

        <form asp-controller="Events" asp-action="Delete" asp-route-id="@Model.Id" method="post">
            <div class="mt-3">
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
        <a class="btn btn-info" asp-controller="Reviews" asp-action="Add" asp-route-id="@Model.Id">Add Reviews</a>
        <a class="btn btn-info" asp-controller="Reviews" asp-action="List" asp-route-id="@Model.Id">List Reviews</a>
    </div>
}
else
{
    <p>Event details not found or the event doesn't exist anymore</p>
}

Views/Events/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<EventManagementSystem.Models.Entities.Event>

<h1>Events</h1>

@foreach(var eventDetails in Model)
{
    <div class="card card-body mb-3">
        <h2>Name: @eventDetails.Name</h2>
        <h3>Price: $@eventDetails.Price</h3>
        <p>Description: @eventDetails.Description</p>
        <span>@eventDetails.Date</span>

        <div class="mt-3">
            <a asp-controller="Events" asp-action="Details" asp-route-id="@eventDetails.Id" class="btn btn-primary">View Details</a>
        </div>
    </div>
}